# Generated by Django 4.1 on 2022-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Slider name')),
                ('about', models.TextField(verbose_name='Slider text')),
                ('img', models.ImageField(upload_to='media', verbose_name='Slider image')),
                ('date', models.DateField(verbose_name='Slider date')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
