# Generated by Django 4.1 on 2022-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Post name')),
                ('about', models.TextField(verbose_name='Post text')),
            ],
            options={
                'verbose_name': 'About2',
                'verbose_name_plural': 'Abouts2',
            },
        ),
        migrations.CreateModel(
            name='About3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Post name')),
                ('about', models.TextField(verbose_name='Post text')),
            ],
            options={
                'verbose_name': 'About3',
                'verbose_name_plural': 'Abouts3',
            },
        ),
        migrations.RenameModel(
            old_name='About',
            new_name='About1',
        ),
        migrations.AlterModelOptions(
            name='about1',
            options={'verbose_name': 'About1', 'verbose_name_plural': 'Abouts1'},
        ),
    ]
